### ISSUE TITLE
Web Admin: Can not create user

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2635]
Tested in Chrome:

```
users#user/create:1 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

6jquery.min.js:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ jquery.min.js:3
T @ jquery.min.js:3
html @ jquery.min.js:3
o.update_results_content @ chosen.jquery.js:972
t.winnow_results @ chosen.jquery.js:399
o.results_show @ chosen.jquery.js:965
o.container_mousedown @ chosen.jquery.js:837
(anonymous) @ chosen.jquery.js:723
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
users#user/create:1 Refused to frame 'https://172.20.145.20:1443/user/create' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
jquery.min.js:2 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://172.20.145.20:1443" from accessing a cross-origin frame.
    at contents (https://172.20.145.20:1443/static/js/vendor/jquery.min.js:2:27438)
    at Function.map (https://172.20.145.20:1443/static/js/vendor/jquery.min.js:2:3309)
    at r.fn.init.r.fn.(anonymous function) [as contents] (https://172.20.145.20:1443/static/js/vendor/jquery.min.js:2:27561)
    at HTMLIFrameElement.<anonymous> (https://172.20.145.20:1443/static/js/user.js:197:32)
    at HTMLIFrameElement.e (https://172.20.145.20:1443/static/js/vendor/jquery.min.js:3:7913)
    at HTMLIFrameElement.dispatch (https://172.20.145.20:1443/static/js/vendor/jquery.min.js:3:10316)
    at HTMLIFrameElement.q.handle (https://172.20.145.20:1443/static/js/vendor/jquery.min.js:3:8343)
```

**Comment by jrouzierinverse** [comment]
Fix in devel
