### ISSUE TITLE
Graphite error because of a missing package

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2693]
I'm getting the following graphite error on my test setup:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 339, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 339, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 223, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 230, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/graphite/render/views.py", line 34, in <module>
    from graphite.render.evaluator import evaluateTarget, extractPathExpressions
  File "/usr/lib/python2.7/site-packages/graphite/render/evaluator.py", line 72, in <module>
    from graphite.render.functions import SeriesFunctions,NormalizeEmptyResultError
  File "/usr/lib/python2.7/site-packages/graphite/render/functions.py", line 34, in <module>
    from graphite.render.glyph import format_units
  File "/usr/lib/python2.7/site-packages/graphite/render/glyph.py", line 20, in <module>
    import cairocffi as cairo
ImportError: No module named cairocffi
```

Comparing with another working setup, it seems a newer graphite version has arised and requires a new module.

My working instance:
```
# yum list installed | grep graphite
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
graphite-web.noarch                    0.9.15-10.1            @packetfence-devel
graphite2.x86_64                       1.3.6-1.el7_2          @updates     
```

My broken instance:
```
[root@localhost pf]# yum list installed | grep graphit
graphite-web.noarch                    0.9.15-10.1            @packetfence-devel
graphite2.x86_64                       1.3.10-1.el7_3         @updates          
```

My guess is we should pin the graphite version in the spec or package any new graphite dependency so we stay up-to-date.

**Comment by julsemaan** [comment]
Opinion, @fdurand ?

**Comment by fdurand** [comment]
graphite2 is another tool that is not used by graphite-web.
Can you check the version of mesa-libEGL ?
Also can you do that:
python
import cairo

**Comment by julsemaan** [comment]
Based on this morning's discussion, it does seem you're right and we'll need to downgrade that lib:

```
[root@localhost pf]# python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/cairo/__init__.py", line 1, in <module>
    from _cairo import *
ImportError: /lib64/libgbm.so.1: undefined symbol: drmGetDevice
```

Problem is that I can't downgrade that lib right now as it isn't in the base repo anymore:
```
[root@localhost pf]# yum list installed mesa-libEGL
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.calgah.com
 * extras: centos.mirror.colo-serv.net
 * updates: mirror.calgah.com
Installed Packages
mesa-libEGL.x86_64                                                                                             17.0.1-6.20170307.el7                                                                                              @base
[root@localhost pf]# yum downgrade mesa-libEGL
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.calgah.com
 * extras: centos.mirror.colo-serv.net
 * updates: mirror.calgah.com
Nothing to do
```

**Comment by fdurand** [comment]
Looks tha it's more related to mesa-libgbm and not mesa-libEGL

**Comment by julsemaan** [comment]
No downgrade available either unfortunately..

**Comment by julsemaan** [comment]
Since I'm the only one to have experienced this and its not a current devel issue, I'll close that one
