### ISSUE TITLE
Fingerbank-collector: Recovered panic for handler MDNS Handler

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3193]
````
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="=================================================" pid=24147
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="Recovered panic for handler MDNS Handler (dns name uncomputable: invalid index)" pid=24147
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="=================================================" pid=24147
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="Recovered panic for handler MDNS Handler (dns name uncomputable: invalid index)" pid=24147
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="goroutine 1714995 [running]:\nruntime/debug.Stack(0xc4201fc660, 0xc4204d8050, 0x4f)\n\t/tmp/tmp.LZ7Q5EOBeC/go/src/runtime/debug/stack.go:24 +0xa7\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket.func1.1(0xc4200804d0, 0xc42062be68)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:885 +0x18e\npanic(0x94b9a0, 0xc4203a8eb0)\n\t/tmp/tmp.LZ7Q5EOBeC/go/src/runtime/panic.go:491 +0x283\ngit.inverse.ca/inverse/fingerbank-collector/handlers/mdns.MDNSHandler.Handle(0xf5afe0, 0xc4200804d0, 0xc420284020, 0xc42001cfc0, 0xc420602126, 0x6, 0x5a, 0xc42001d010, 0xb, 0xc420602120, ...)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/handlers/mdns/mdns.go:75 +0x4e6\ngit.inverse.ca/inverse/fingerbank-collector/handlers/mdns.(*MDNSHandler).Handle(0xc4200d37e0, 0xc420602126, 0x6, 0x5a, 0xc42001d010, 0xb, 0xc420602120, 0x6, 0x60, 0xc42001d033, ...)\n\t<autogenerated>:1 +0xee\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket.func1(0xc4200804d0, 0xc420311e68, 0xc420602126, 0x6, 0x5a, 0xc42001d010, 0xb, 0xc420602120, 0x6, 0x60, ...)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:890 +0x105\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket(0xc4200804d0, 0xc42026a280, 0xf5bce0, 0xc4205b52c0, 0x0, 0x45fdf6)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:891 +0x40f\nmain.captureAndProcess.func1.2(0xc42006cd70, 0xc42026a280, 0xf5bce0, 0xc4205b52c0)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/capture.go:239 +0x4b\ncreated by main.captureAndProcess.func1\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/capture.go:238 +0x20a\n" pid=24147
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="=================================================" pid=24147
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="goroutine 1714994 [running]:\nruntime/debug.Stack(0xc4201fc660, 0xc420512050, 0x4f)\n\t/tmp/tmp.LZ7Q5EOBeC/go/src/runtime/debug/stack.go:24 +0xa7\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket.func1.1(0xc4200804d0, 0xc420047e68)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:885 +0x18e\npanic(0x94b9a0, 0xc4205c0390)\n\t/tmp/tmp.LZ7Q5EOBeC/go/src/runtime/panic.go:491 +0x283\ngit.inverse.ca/inverse/fingerbank-collector/handlers/mdns.MDNSHandler.Handle(0xf5afe0, 0xc4200804d0, 0xc420284020, 0xc42001cfc0, 0xc4206020c6, 0x6, 0x5a, 0xc4203b4cd0, 0xb, 0xc4206020c0, ...)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/handlers/mdns/mdns.go:75 +0x4e6\ngit.inverse.ca/inverse/fingerbank-collector/handlers/mdns.(*MDNSHandler).Handle(0xc4200d37e0, 0xc4206020c6, 0x6, 0x5a, 0xc4203b4cd0, 0xb, 0xc4206020c0, 0x6, 0x60, 0xc4203b4ce3, ...)\n\t<autogenerated>:1 +0xee\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket.func1(0xc4200804d0, 0xc42036ce68, 0xc4206020c6, 0x6, 0x5a, 0xc4203b4cd0, 0xb, 0xc4206020c0, 0x6, 0x60, ...)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:890 +0x105\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket(0xc4200804d0, 0xc42026a280, 0xf5bce0, 0xc4205b5180, 0x0, 0x45fdf6)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:891 +0x40f\nmain.captureAndProcess.func1.2(0xc42006cd70, 0xc42026a280, 0xf5bce0, 0xc4205b5180)\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/capture.go:239 +0x4b\ncreated by main.captureAndProcess.func1\n\t/tmp/tmp.ZyjSHKeXR2/src/git.inverse.ca/inverse/fingerbank-collector/capture.go:238 +0x20a\n" pid=24147
Apr 25 16:40:43 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[24147]: t=2018-04-25T16:40:43-0400 lvl=eror msg="=================================================" pid=24147
````

**Comment by julsemaan** [comment]
I'll adjust it so that it logs it instead of creating a panic in the code.

Not sure we can find exactly the issue now, its likely an unexpected mDNS packet format

**Comment by julsemaan** [comment]
It will be in the next fingerbank-collector package tomorrow morning so check it out and close the issue if its fine

**Comment by extrafu** [comment]
Lowered importance if we no longer panic. Only @lzammit panics.

**Comment by julsemaan** [comment]
@lzammit 

Can you confirm this is fixed ?

**Comment by lzammit** [comment]
Looks fixaide!
