### ISSUE TITLE
Fingerbank-collector: Recovered panic for handler Radius Accounting Handler

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#3202]
````
Apr 26 10:10:27 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[28782]: t=2018-04-26T10:10:27-0400 lvl=eror msg="=================================================" pid=28782
Apr 26 10:10:27 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[28782]: t=2018-04-26T10:10:27-0400 lvl=eror msg="Recovered panic for handler Radius Accounting Handler (runtime error: slice bounds out of range)" pid=28782
Apr 26 10:10:27 testing-c7 /usr/local/fingerbank/collector/fingerbank-collector[28782]: t=2018-04-26T10:10:27-0400 lvl=eror msg="goroutine 1321925 [running]:\nruntime/debug.Stack(0xc420234680, 0xc420064300, 0x60)\n\t/tmp/tmp.UUPwCiXNpV/go/src/runtime/debug/stack.go:24 +0xa7\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket.func1.1(0xc420098580, 0xc42004be68)\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:885 +0x18e\npanic(0x972c20, 0xf68000)\n\t/tmp/tmp.UUPwCiXNpV/go/src/runtime/panic.go:491 +0x283\ngit.inverse.ca/inverse/fingerbank-collector/vendor/github.com/bronze1man/radius.DecodePacket(0xa1c2b3, 0x6, 0xc4200a65ae, 0x11d, 0x11d, 0xb, 0x2, 0x2)\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/vendor/github.com/bronze1man/radius/packet.go:201 +0x4d4\ngit.inverse.ca/inverse/fingerbank-collector/handlers/radius.RadiusHandler.Parse(0xf86a20, 0xc420098580, 0xc4200a65ae, 0x11d, 0x11d, 0xa410da, 0x29, 0xc4202c8ca0)\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/handlers/radius/radius.go:76 +0x54\ngit.inverse.ca/inverse/fingerbank-collector/handlers/radius.RadiusHandler.Handle(0xf86a20, 0xc420098580, 0xc4200a6586, 0x6, 0x145, 0xc42001cc60, 0xd, 0xc4200a6580, 0x6, 0x14b, ...)\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/handlers/radius/radius.go:30 +0x74\ngit.inverse.ca/inverse/fingerbank-collector/handlers/radius.(*RadiusHandler).Handle(0xc4204a8cc0, 0xc4200a6586, 0x6, 0x145, 0xc42001cc60, 0xd, 0xc4200a6580, 0x6, 0x14b, 0xc42001cc80, ...)\n\t<autogenerated>:1 +0xd6\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket.func1(0xc420098580, 0xc4202c8e68, 0xc4200a6586, 0x6, 0x145, 0xc42001cc60, 0xd, 0xc4200a6580, 0x6, 0x14b, ...)\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:890 +0x105\ngit.inverse.ca/inverse/fingerbank-collector/common.(*FingerbankCollector).HandleGoPacket(0xc420098580, 0xc4203ebc00, 0xf87720, 0xc4201e9cc0, 0x0, 0x4602a6)\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/common/collector.go:891 +0x40f\nmain.captureAndProcess.func1.2(0xc42028ab40, 0xc4203ebc00, 0xf87720, 0xc4201e9cc0)\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/capture.go:246 +0x4b\ncreated by main.captureAndProcess.func1\n\t/tmp/tmp.IMSdez28iN/src/git.inverse.ca/inverse/fingerbank-collector/capture.go:245 +0x20a\n" pid=28782
````

**Comment by julsemaan** [comment]
We will disable the RADIUS accounting sensor for 8.0 and rebuild packages

We shall address this in the collector after the release

**Comment by julsemaan** [comment]
package for CentOS is done, its being synced into devel

**Comment by julsemaan** [comment]
@fdurand updated the package in devel
