### ISSUE TITLE
Golang unit test failure: API AAA test auth backend

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3738]
```
--- FAIL: TestDbAuthenticationBackend (0.14s)
        db_authentication_backend_test.go:33: Auth failed for a valid user Error 1146: Table 'pf_smoke_test.api_user' doesn't exist
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73c456]

goroutine 15 [running]:
testing.tRunner.func1(0xc4200fa5a0)
        /usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x7a29e0, 0xa110c0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/inverse-inc/packetfence/go/api-frontend/aaa.TestDbAuthenticationBackend(0xc4200fa5a0)
        /tmp/tmp.VRZflnL44V/src/github.com/inverse-inc/packetfence/go/api-frontend/aaa/db_authentication_backend_test.go:36 +0x336
testing.tRunner(0xc4200fa5a0, 0x824d08)
        /usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:789 +0x2de
FAIL    github.com/inverse-inc/packetfence/go/api-frontend/aaa  1.183s
```

**Comment by julsemaan** [comment]
fixed by f2257207a380c149af63938a46244125fe37ebb7
