### ISSUE TITLE
pfstats not started

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#3875]
After a fresh install (CentOS 7), pfstats not started.

If I start it by hand:
```console
# /usr/local/pf/sbin/pfstats
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6b51c4]

goroutine 50 [running]:
github.com/inverse-inc/packetfence/go/log.AddToLogContext(0x0, 0x0, 0xc420365dc8, 0x2, 0x2, 0x4, 0x7549a2)
        /tmp/tmp.wf6XPODJbd/src/github.com/inverse-inc/packetfence/go/log/log.go:199 +0x84
github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocketCache(0x0, 0x0, 0xa26b80, 0xc4202f81b0, 0xc0, 0x7e6040, 0x1)
        /tmp/tmp.wf6XPODJbd/src/github.com/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:286 +0x149
github.com/inverse-inc/packetfence/go/pfconfigdriver.FindClusterName(0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.wf6XPODJbd/src/github.com/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:254 +0xb6
main.detectVIP(0xbf0043e6f4b7787c, 0x18792ad, 0xa5dbe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/tmp.wf6XPODJbd/src/github.com/inverse-inc/packetfence/go/stats/main.go:1788 +0x68
main.main.func6(0xc420292160)
        /tmp/tmp.wf6XPODJbd/src/github.com/inverse-inc/packetfence/go/stats/main.go:355 +0x5b
created by main.main
        /tmp/tmp.wf6XPODJbd/src/github.com/inverse-inc/packetfence/go/stats/main.go:353 +0x45b

```

**Comment by julsemaan** [comment]
Getting the same thing on my machine, this is because the new VIP check that was added runs even though the server is not in a cluster.

I'll look into this
