### ISSUE TITLE
Concurrent map write in pfdns causes crash

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5435]
**Describe the bug**
```
May 12 08:55:36 vPF3 pfdns[17054]: fatal error: concurrent map writes
May 12 08:55:36 vPF3 pfdns[17054]: goroutine 98 [running]:
May 12 08:55:36 vPF3 pfdns[17054]: runtime.throw(0xd79f84, 0x15)
May 12 08:55:36 vPF3 pfdns[17054]: /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000202a18 sp=0xc0002029e8 pc=0x430e52
May 12 08:55:36 vPF3 pfdns[17054]: runtime.mapassign_fast64ptr(0xc46fe0, 0xc0004c0c30, 0xc0003d63c0, 0x10)
May 12 08:55:36 vPF3 pfdns[17054]: /usr/local/go/src/runtime/map_fast64.go:191 +0x369 fp=0xc000202a58 sp=0xc000202a18 pc=0x4139d9
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/pfdns.(*pfdns).detectVIP(0xc0001361e0, 0x0, 0x0)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/plugin/pfdns/pfconfig.go:137 +0xaf2 fp=0xc000202c38 sp=0xc000202a58 pc=0xad0772
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/pfdns.(*pfdns).ServeDNS(0xc0001361e0, 0xe95fa0, 0xc0004e2ab0, 0xe9cc60, 0xc000176240, 0xc000276fc0, 0x40dd26, 0xc000379360, 0x0)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/plugin/pfdns/pfdns.go:393 +0x2bd1 fp=0xc000203330 sp=0xc000202c38 pc=0xad3e91
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/logger.Logger.ServeDNS(0xe8b1c0, 0xc0001361e0, 0xe95fa0, 0xc0001b1bc0, 0xe95f20, 0xc0000c6010, 0xe9cc60, 0xc000176240, 0xc000276fc0, 0x0, ...)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/plugin/logger/logger.go:72 +0xb7 fp=0xc000203388 sp=0xc000203330 pc=0xa5fc17
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/logger.(*Logger).ServeDNS(0xc000358220, 0xe95f20, 0xc0000c6010, 0xe9cc60, 0xc000176240, 0xc000276fc0, 0xc0003234d8, 0x6fa602, 0xc000335020)
May 12 08:55:36 vPF3 pfdns[17054]: <autogenerated>:1 +0xa1 fp=0xc0002033f8 sp=0xc000203388 pc=0xa5ff31
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin.NextOrFailure(0xd6ab84, 0x3, 0xe8e0c0, 0xc000358220, 0xe95f20, 0xc0000c6010, 0xe9cc60, 0xc000176240, 0xc000276fc0, 0x0, ...)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/plugin/plugin.go:79 +0xe6 fp=0xc000203520 sp=0xc0002033f8 pc=0x7f4066
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/log.Logger.ServeDNS(0xe8e0c0, 0xc000358220, 0xc0001c0640, 0x1, 0x1, 0xda57f8, 0xe95f20, 0xc0000c6010, 0xe9e880, 0xc000126e00, ...)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/plugin/log/log.go:36 +0x39d fp=0xc000203730 sp=0xc000203520 pc=0xa4b1ed
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/log.(*Logger).ServeDNS(0xc0003377d0, 0xe95f20, 0xc0000c6010, 0xe9e880, 0xc000126e00, 0xc000276fc0, 0xf1, 0xc0003238b8, 0x1a)
May 12 08:55:36 vPF3 pfdns[17054]: <autogenerated>:1 +0xd6 fp=0xc0002037e0 sp=0xc000203730 pc=0xa4cd56
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin.NextOrFailure(0xd6ca0b, 0x6, 0xe8e080, 0xc0003377d0, 0xe95f20, 0xc0000c6010, 0xe9e880, 0xc000126e00, 0xc000276fc0, 0x0, ...)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/plugin/plugin.go:79 +0xe6 fp=0xc000203908 sp=0xc0002037e0 pc=0x7f4066
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/errors.errorHandler.ServeDNS(0xe8e080, 0xc0003377d0, 0xd6d0dd, 0x6, 0xc0000cf360, 0xe95f20, 0xc0000c6010, 0xe9e880, 0xc000126e00, 0xc000276fc0, ...)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/plugin/errors/errors.go:29 +0x170 fp=0xc000203b00 sp=0xc000203908 pc=0x9cad50
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/plugin/errors.(*errorHandler).ServeDNS(0xc000337800, 0xe95f20, 0xc0000c6010, 0xe9e880, 0xc000126e00, 0xc000276fc0, 0x8, 0x20, 0xc000358ac0)
May 12 08:55:36 vPF3 pfdns[17054]: <autogenerated>:1 +0xd0 fp=0xc000203ba0 sp=0xc000203b00 pc=0x9cc230
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/core/dnsserver.(*Server).ServeDNS(0xc00017a060, 0xe95f20, 0xc0000c6010, 0xe9e880, 0xc000126e00, 0xc000276fc0)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/core/dnsserver/server.go:269 +0x366 fp=0xc000203ce8 sp=0xc000203ba0 pc=0x9830b6
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/core/dnsserver.(*Server).ServePacket.func1(0xe9e880, 0xc000126e00, 0xc000276fc0)
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/core/dnsserver/server.go:111 +0x60 fp=0xc000203d28 sp=0xc000203ce8 pc=0x984000
May 12 08:55:36 vPF3 pfdns[17054]: github.com/miekg/dns.HandlerFunc.ServeDNS(0xc000078000, 0xe9e880, 0xc000126e00, 0xc000276fc0)
May 12 08:55:36 vPF3 pfdns[17054]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:52 +0x44 fp=0xc000203d50 sp=0xc000203d28 pc=0x6f0624
May 12 08:55:36 vPF3 pfdns[17054]: github.com/miekg/dns.(*Server).serveDNS(0xc0001d6000, 0xc000126e00)
May 12 08:55:36 vPF3 pfdns[17054]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:687 +0x292 fp=0xc000203dd8 sp=0xc000203d50 pc=0x6f3072
May 12 08:55:36 vPF3 pfdns[17054]: github.com/miekg/dns.(*Server).serve(0xc0001d6000, 0xc000126e00)
May 12 08:55:36 vPF3 pfdns[17054]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:572 +0x2eb fp=0xc000203ea0 sp=0xc000203dd8 pc=0x6f2c6b
May 12 08:55:36 vPF3 pfdns[17054]: github.com/miekg/dns.(*Server).worker(0xc0001d6000, 0xc0003c1180)
May 12 08:55:36 vPF3 pfdns[17054]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:269 +0x200 fp=0xc000203fd0 sp=0xc000203ea0 pc=0x6f0b90
May 12 08:55:36 vPF3 pfdns[17054]: runtime.goexit()
May 12 08:55:36 vPF3 pfdns[17054]: /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000203fd8 sp=0xc000203fd0 pc=0x460991
May 12 08:55:36 vPF3 pfdns[17054]: created by github.com/miekg/dns.(*Server).spawnWorker
May 12 08:55:36 vPF3 pfdns[17054]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:284 +0x83
May 12 08:55:36 vPF3 pfdns[17054]: goroutine 1 [semacquire]:
May 12 08:55:36 vPF3 pfdns[17054]: sync.runtime_Semacquire(0xc0000c7708)
May 12 08:55:36 vPF3 pfdns[17054]: /usr/local/go/src/runtime/sema.go:56 +0x42
May 12 08:55:36 vPF3 pfdns[17054]: sync.(*WaitGroup).Wait(0xc0000c7700)
May 12 08:55:36 vPF3 pfdns[17054]: /usr/local/go/src/sync/waitgroup.go:130 +0x64
May 12 08:55:36 vPF3 pfdns[17054]: github.com/mholt/caddy.(*Instance).Wait(...)
May 12 08:55:36 vPF3 pfdns[17054]: /root/go/pkg/mod/github.com/mholt/caddy@v0.9.5/caddy.go:382
May 12 08:55:36 vPF3 pfdns[17054]: github.com/inverse-inc/packetfence/go/coredns/coremain.Run()
May 12 08:55:36 vPF3 pfdns[17054]: /builds/inverse-inc/packetfence/go/coredns/coremain/run.go:111 +0x290
May 12 08:55:36 vPF3 pfdns[17054]: main.main()
```

**Comment by julsemaan** [comment]
It seems detectVIP() may be called by multiple go routines

This needs a locking mechanism to only run detectVIP once at a time
