### ISSUE TITLE
PacketFence-PKI services does not start on a new cluster installation

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5551]
````
Build: packetfence-10.0.9-20200608183456.154110102.0007.devel.el7.x86_64
````

````
Jun 08 16:04:20 cluster2.inverse.ca /usr/local/pf/sbin/pfhttpd[16104]: t=2020-06-08T16:04:20-0400 lvl=dbug msg="Adding struct with address 0x1c0bd40 to the pool" pid=16104
Jun 08 16:04:20 cluster2.inverse.ca /usr/local/pf/sbin/pfhttpd[16104]: t=2020-06-08T16:04:20-0400 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00
Jun 08 16:04:20 cluster2.inverse.ca /usr/local/pf/sbin/pfhttpd[16104]: t=2020-06-08T16:04:20-0400 lvl=dbug msg="Adding struct with address 0x1c0bd40 to the pool" pid=16104
Jun 08 16:04:20 cluster2.inverse.ca pfpki[16104]: t=2020-06-08T16:04:20-0400 lvl=dbug msg="Adding struct with address 0x1c0bd40 to the pool" pid=16104
Jun 08 16:04:20 cluster2.inverse.ca systemd[1]: Started PacketFence PKI Daemon.
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: Unable to connect to database to get multi-tenant status: dial tcp 127.0.0.1:3306: connect: connection refusedActivating
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: Using configuration set log level: INFO
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: panic: dial tcp 127.0.0.1:3306: connect: connection refused
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: goroutine 1 [running]:
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/sharedutils.CheckError(...)
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/sharedutils/util.go:119
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/caddy/pfpki.buildPfpkiHandler(0x127c820, 0xc00044f380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/pfpki/pfpki.go:68 +0xf08
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/caddy/pfpki.setup(0xc0001c8d80, 0x4, 0x10c632d)
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/pfpki/pfpki.go:51 +0xaf
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/caddy/caddy.executeDirectives(0xc000435800, 0x7fffdfa14c38, 0x2c, 0x1b9d640, 0x54,
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:682 +0x69e
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/caddy/caddy.ValidateAndExecuteDirectives(0x1278fe0, 0xc000456200, 0xc000435800, 0x0
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:638 +0x55e
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/caddy/caddy.startWithListenerFds(0x1278fe0, 0xc000456200, 0xc000435800, 0x0, 0x0, 0
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:533 +0x13c
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/caddy/caddy.Start(0x1278fe0, 0xc000456200, 0x0, 0x0, 0x0)
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:490 +0x14b
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: github.com/inverse-inc/packetfence/go/caddy/caddy/caddy/caddymain.Run()
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy/caddymain/run.go:217 +0x739
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: main.main()
Jun 08 16:04:20 cluster2.inverse.ca pfhttpd[16104]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy/main.go:27 +0x27
Jun 08 16:04:20 cluster2.inverse.ca systemd[1]: packetfence-pfpki.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 08 16:04:20 cluster2.inverse.ca systemd[1]: Unit packetfence-pfpki.service entered failed state.
Jun 08 16:04:20 cluster2.inverse.ca systemd[1]: packetfence-pfpki.service failed.
Jun 08 16:04:20 cluster2.inverse.ca systemd[1]: packetfence-pfpki.service holdoff time over, scheduling restart.
Jun 08 16:04:20 cluster2.inverse.ca systemd[1]: Stopped PacketFence PKI Daemon.
Jun 08 16:04:20 cluster2.inverse.ca systemd[1]: Starting PacketFence PKI Daemon.
````

**Comment by fdurand** [comment]
Do you have something listening on 127.0.0.1:3306?

**Comment by julsemaan** [comment]
I think that may actually my bad, its to get the multi-tenant status when starting but I guess the DB isn't started yet.

I'll have to adjust the code so that if it fails to do it on startup, it does it during API requests until this succeeds
