### ISSUE TITLE
api-frontend seems to crash after receiving bad accounting data

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5565]
**Describe the bug**
`api-frontend` crashs with message below without any reason:

```
Jun 09 11:06:02 pfserver pfhttpd[3736]: api-frontend-access 127.0.0.1 - - [09/Jun/2020:11:06:02 +0200] "GET /api/v1/queues/stats HTTP/1.1" 200 844 "-" "Go-http-client/1.1"
Jun 09 11:06:03 pfserver pfhttpd[3736]: panic: json: cannot unmarshal string into Go struct field PfConfAdvanced.accounting_timebucket_size of type int
Jun 09 11:06:03 pfserver pfhttpd[3736]: goroutine 88 [running]:
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeJsonInterface(0x108e440, 0xc0003776b0, 0xc0000dd200, 0x455, 0x480, 0xd645a0, 0xc000278d50)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:212 +0x1c6
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeInterface(0x108e440, 0xc0003776b0, 0xf17106, 0x4, 0xc0000dd200, 0x455, 0x480, 0xd645a0, 0xc000278d50)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:198 +0x8f
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocket(0x108e440, 0xc0003776b0, 0x7f720bf5c618, 0x192b958, 0x0, 0x108e440)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:392 +0x67f
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocketCache(0x108e440, 0xc0003776b0, 0x7f720bf5c618, 0x192b958, 0x192b958, 0x192b901, 0x500000000000000)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/pfconfigdriver/fetch.go:348 +0x28a
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).refreshStruct(0x19282a0, 0x108e440, 0xc00038d950, 0xdee980, 0x192b958)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/pfconfigdriver/pool.go:104 +0x324
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).refreshStructs(0x19282a0, 0x108e440, 0xc00038d950)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/pfconfigdriver/pool.go:120 +0xbc
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).Refresh(0x19282a0, 0x108e440, 0xc00038d950, 0x461000)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/pfconfigdriver/pool.go:160 +0x24b
Jun 09 11:06:03 pfserver pfhttpd[3736]: github.com/inverse-inc/packetfence/go/caddy/pfconfig.PoolHandler.ServeHTTP.func1.1(0x108e440, 0xc00038d950)
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/caddy/pfconfig/pool.go:47 +0x41
Jun 09 11:06:03 pfserver pfhttpd[3736]: created by github.com/inverse-inc/packetfence/go/caddy/pfconfig.PoolHandler.ServeHTTP.func1
Jun 09 11:06:03 pfserver pfhttpd[3736]:         /builds/inverse-inc/packetfence/go/caddy/pfconfig/pool.go:45 +0x56
Jun 09 11:06:03 pfserver systemd[1]: packetfence-api-frontend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 09 11:06:03 pfserver systemd[1]: packetfence-api-frontend.service: Unit entered failed state.
Jun 09 11:06:03 pfserver systemd[1]: packetfence-api-frontend.service: Failed with result 'exit-code'.
Jun 09 11:06:04 pfserver systemd[1]: packetfence-api-frontend.service: Service hold-off time over, scheduling restart.
Jun 09 11:06:04 pfserver systemd[1]: Stopped PacketFence API frontend Service.
```

At same time, I'm able to see this data in accounting:
```console
# pfcmd cache accounting dump 0
$VAR1 = {                             
          'Realm' => 'null',                         
          'NAS-Identifier' => 'WLC1',            
          'Stripped-User-Name' => 'cisco-probe',        
          'Acct-Unique-Session-Id' => 'a78c4f84420fa56737366db3ce712378',
          'Event-Timestamp' => 'Nov 14 2019 13:02:47 CET',   
          'FreeRADIUS-Client-IP-Address' => '172.17.0.29',
          'User-Name' => 'cisco-probe',
          'Proxy-State' => '0x313934',
          'Acct-Session-Id' => "e\x{cb}i",
          'Acct-Status-Type' => 1,
          'NAS-IP-Address' => '10.0.17.10',
          'Called-Station-Id' => '10.0.17.10',
          'Acct-Authentic' => 1,
          'Calling-Station-Id' => '10.0.17.10'
        };
```

**Comment by nqb** [comment]
I tried to forge accounting request using:
```
# cat > /opt/acct << EOF
NAS-Identifier = "WLC1"
Stripped-User-Name = "cisco-probe"        
Acct-Unique-Session-Id = "a78c4f84420fa56737366db3ce712378"
Event-Timestamp = "Nov 14 2019 13:02:47 CET"   
FreeRADIUS-Client-IP-Address = 172.17.0.29
User-Name = "cisco-probe"
Proxy-State = 0x313934
Acct-Session-Id = "e\x{cb}i"
Acct-Status-Type = 1
NAS-IP-Address = 192.168.1.1
Called-Station-Id = 192.168.1.1
Acct-Authentic = 1
Calling-Station-Id = 192.168.1.1
EOF

# cat /opt/acct | radclient -x 172.17.17.12:1813 acct `cat /usr/local/pf/conf/local_secret`
```
Accounting data is handle correctly but not store exactly like I expect:

```console
# pfcmd cache accounting dump 0
$VAR1 = {
          'Acct-Session-Id' => 'e\\x{cb}i',
          'Acct-Status-Type' => 1,
          'NAS-Identifier' => 'WLC1',
          'User-Name' => 'cisco-probe',
          'NAS-IP-Address' => '192.168.1.1',
          'Event-Timestamp' => '2019-11-14 13:02:47 +0000 UTC',
          'Calling-Station-Id' => '192.168.1.1',
          'Acct-Authentic' => 1,
          'Called-Station-Id' => '192.168.1.1'
        };
```

No crash on `api-frontend`. 

@jrouzierinverse, it could be caused by other things. I will let you take the lead on this issue. Feel free to close if not relevant.

**Comment by jrouzierinverse** [comment]
Please provide the output of this command
```
./bin/pfcmd pfconfig show config::Pf | json_xs -f eval | jq .advanced.accounting_timebucket_size
```

**Comment by nqb** [comment]
On my devel setup where I tried to reproduce issue:

```
# pfcmd pfconfig show config::Pf | json_xs -f eval | jq .advanced.accounting_timebucket_size
300
```

It's on Debian. Customer was running Debian too.

**Comment by jrouzierinverse** [comment]
Was this a one time error or does it keep on happening?
From looking at the stack trace advanced.accounting_timebucket_size was not properly serialized as an integer for some reason.
Maybe after an upgrade or patch, there was no ```./bin/pfcmd configreload``` done.

**Comment by nqb** [comment]
> Was this a one time error or does it keep on happening?

One time error. Let's close this and if it occurs again I will go deep.

**Comment by nqb** [comment]
Hello @jrouzierinverse,

I got a similar error during an upgrade from 9.1.0 to 10.1.0 in a cluster environment on CentOS 7.

I was testing if accounting works as expected on node C [at this step](https://packetfence.org/doc/PacketFence_Clustering_Guide.html#_start_service_on_node_c) after I restart services using instructions mentioned in link.

`pfacct` was not able to handle any accounting requests. So I tried to disable `pfacct` service using GUI and enable `radiusd-acct` as a workaround. Immediately after I saved my change, `api-frontend` crashs:

```
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: api-frontend-access 10.104.100.43 - - [30/Sep/2020:09:58:29 +0200] "PATCH /api/v1/config/base/services HTTP/1.1" 200 43 "https://vjnac.villejuif.fr:1443/admin/alt" "Mozil
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: panic: json: cannot unmarshal string into Go struct field PfConfAdvanced.accounting_timebucket_size of type int
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: goroutine 3124 [running]:
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeJsonInterface(0x127ca40, 0xc0007816e0, 0xc00010a900, 0x472, 0x480, 0xecb620, 0xc0001aac20)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/pfconfigdriver/fetch.go:212 +0x1c6
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeInterface(0x127ca40, 0xc0007816e0, 0x10c5310, 0x4, 0xc00010a900, 0x472, 0x480, 0xecb620, 0xc0001aac20)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/pfconfigdriver/fetch.go:198 +0x8f
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocket(0x127ca40, 0xc0007816e0, 0x7f2ed98ff488, 0x1c0b798, 0x0, 0x127ca40)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/pfconfigdriver/fetch.go:392 +0x67f
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocketCache(0x127ca40, 0xc0007816e0, 0x7f2ed98ff488, 0x1c0b798, 0x1c0b798, 0x1c0b701, 0x300000000000000)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/pfconfigdriver/fetch.go:348 +0x28a
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).refreshStruct(0x1c07180, 0x127ca40, 0xc0006da7b0, 0xf6d1a0, 0x1c0b798)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/pfconfigdriver/pool.go:104 +0x324
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).refreshStructs(0x1c07180, 0x127ca40, 0xc0006da7b0)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/pfconfigdriver/pool.go:120 +0xbc
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/pfconfigdriver.(*Pool).Refresh(0x1c07180, 0x127ca40, 0xc0006da7b0, 0x461500)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/pfconfigdriver/pool.go:160 +0x24b
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: github.com/inverse-inc/packetfence/go/caddy/pfconfig.PoolHandler.ServeHTTP.func1.1(0x127ca40, 0xc0006da7b0)
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/caddy/pfconfig/pool.go:47 +0x41
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: created by github.com/inverse-inc/packetfence/go/caddy/pfconfig.PoolHandler.ServeHTTP.func1
sept. 30 09:58:29 VJNAC3 pfhttpd[35677]: /root/rpmbuild/centos-7/BUILD/packetfence-10.1.0/go/caddy/pfconfig/pool.go:45 +0x56
sept. 30 09:58:29 VJNAC3 systemd[1]: packetfence-api-frontend.service: main process exited, code=exited, status=2/INVALIDARGUMENT
sept. 30 09:58:29 VJNAC3 systemd[1]: Unit packetfence-api-frontend.service entered failed state.
sept. 30 09:58:29 VJNAC3 systemd[1]: packetfence-api-frontend.service failed.
```

I revert my changes by editing directly `pf.conf`, re-run a `configreload hard` and restart `api-frontend` service: issue was gone. Few minutes after, I started again `pfacct` and it starts to work.

I'm not able to replicate this issue if I disable `pfacct` in GUI on a standalone server.

My feeling is that this issue is specific to a cluster upgrade (last error reported was during a cluster upgrade too). Perhaps because we don't use [usual instructions to restart services ](https://packetfence.org/doc/PacketFence_Upgrade_Guide.html#_restart_all_packetfence_services). We dont run:

```
/usr/local/pf/bin/pfcmd pfconfig clear_backend
systemctl restart packetfence-config
```

I have another cluster upgrade schedule next week, let me know if you want me to test something.

**Comment by jrouzierinverse** [comment]
This sounds like the DocConfig was not properly reloaded since the accounting_timebucket_size was not turned into an integer.

**Comment by jrouzierinverse** [comment]
This will only happen during an upgrade cfabb3b should fix it.

**Comment by nqb** [comment]
Could you backport that to maintenance/10.1 to avoid issue when doing an upgrade ?
