### ISSUE TITLE
PacketFence PKI: Fails after a pf restart

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5570]
````
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: Unable to connect to database to get multi-tenant status: dial tcp 127.0.0.1:3306: connect: connection refused
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: Activating privacy features... done.
Jun 10 16:55:36 cluster1.inverse.ca pfpki[32347]: t=2020-06-10T16:55:36-0400 lvl=dbug msg="Adding struct with address 0x1c0bd60 to the pool" pid=32347
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: Using configuration set log level: INFO
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: Started PacketFence PKI Daemon.
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: panic: dial tcp 127.0.0.1:3306: connect: connection refused
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: goroutine 1 [running]:
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/sharedutils.CheckError(...)
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/sharedutils/util.go:119
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/caddy/pfpki.buildPfpkiHandler(0x127ca20, 0xc000459590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/pfpki/pfpki.go:68 +0xf08
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/caddy/pfpki.setup(0xc00017f200, 0x4, 0x10c648d)
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/pfpki/pfpki.go:51 +0xaf
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/caddy/caddy.executeDirectives(0xc00043d800, 0x7ffda13bcc38, 0x2c, 0x1b9d660, 0x54,
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:682 +0x69e
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/caddy/caddy.ValidateAndExecuteDirectives(0x12791e0, 0xc000462240, 0xc00043d800, 0x0
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:638 +0x55e
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/caddy/caddy.startWithListenerFds(0x12791e0, 0xc000462240, 0xc00043d800, 0x0, 0x0, 0
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:533 +0x13c
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/caddy/caddy.Start(0x12791e0, 0xc000462240, 0x0, 0x0, 0x0)
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy.go:490 +0x14b
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: github.com/inverse-inc/packetfence/go/caddy/caddy/caddy/caddymain.Run()
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy/caddymain/run.go:217 +0x739
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: main.main()
Jun 10 16:55:36 cluster1.inverse.ca pfhttpd[32347]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/caddy/caddy/caddy/main.go:27 +0x27
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: packetfence-pfpki.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: Unit packetfence-pfpki.service entered failed state.
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: packetfence-pfpki.service failed.
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: packetfence-pfpki.service holdoff time over, scheduling restart.
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: Stopped PacketFence PKI Daemon.
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: start request repeated too quickly for packetfence-pfpki.service
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: Failed to start PacketFence PKI Daemon.
Jun 10 16:55:36 cluster1.inverse.ca systemd[1]: Unit packetfence-pfpki.service entered failed state.
````

It looks like it tries to connect to the DB after the restart and can't succeed.

If I restart it manually after the pf restart it works.

**Comment by fdurand** [comment]
is it on a cluster ?

**Comment by lzammit** [comment]
Correct!
