### ISSUE TITLE
pfacct doesn't start 

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5579]
**Describe the bug**
on restart on a cluster setup pfacct doesn't start

```
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: panic: dial tcp 127.0.0.1:3306: connect: connection refused
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: goroutine 1 [running]:
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: main.(*RadiusStatements).Setup(0xc000080340, 0xc0002e00c0)
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/acct/radius.go:453 +0x6ea
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: main.NewPfAcct(0x0)
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/acct/pfacct.go:49 +0x149
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: main.main()
jun 12 11:41:35 pf3.baguettefence.org pfacct[18448]: /root/rpmbuild/centos-7/BUILD/packetfence-10.0.9/go/acct/main.go:20 +0x5f
```

**Comment by julsemaan** [comment]
I guess we need a retry logic to connect to the DB since haproxy-db starts after pfacct
