### ISSUE TITLE
pfdns crashes on concurrent map write when there is enough load

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5876]
**Describe the bug**
pfdns crashes consistently when there is enough load on it due to a concurrent map write (trace below is for 10.0)

```
Sep 30 14:51:22 vPF2 pfdns[9640]: goroutine 46 [running]:
Sep 30 14:51:22 vPF2 pfdns[9640]: runtime.throw(0xd79f84, 0x15)
Sep 30 14:51:22 vPF2 pfdns[9640]: /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00035ea18 sp=0xc00035e9e8 pc=0x430e52
Sep 30 14:51:22 vPF2 pfdns[9640]: runtime.mapassign_fast64ptr(0xc46fe0, 0xc00041ec00, 0xc0001c2d20, 0x10)
Sep 30 14:51:22 vPF2 pfdns[9640]: /usr/local/go/src/runtime/map_fast64.go:191 +0x369 fp=0xc00035ea58 sp=0xc00035ea18 pc=0x4139d9
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/pfdns.(*pfdns).detectVIP(0xc00023c000, 0xc00041ea80, 0xc00035f0e0)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/plugin/pfdns/pfconfig.go:137 +0xaf2 fp=0xc00035ec38 sp=0xc00035ea58 pc=0xad0772
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/pfdns.(*pfdns).ServeDNS(0xc00023c000, 0xe95fa0, 0xc0003a8d20, 0xe9cc60, 0xc0003ba840, 0xc000315950, 0x40dd26, 0xc00008c0d8, 0xc00035f3f0)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/plugin/pfdns/pfdns.go:393 +0x2bd1 fp=0xc00035f330 sp=0xc00035ec38 pc=0xad3e91
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/logger.Logger.ServeDNS(0xe8b1c0, 0xc00023c000, 0xe95fa0, 0xc0001dae10, 0xe95f20, 0xc00003e060, 0xe9cc60, 0xc0003ba840, 0xc000315950, 0x0, ...)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/plugin/logger/logger.go:72 +0xb7 fp=0xc00035f388 sp=0xc00035f330 pc=0xa5fc17
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/logger.(*Logger).ServeDNS(0xc00029b080, 0xe95f20, 0xc00003e060, 0xe9cc60, 0xc0003ba840, 0xc000315950, 0xc00035f4d8, 0x6fa602, 0xc0002e2fa0)
Sep 30 14:51:22 vPF2 pfdns[9640]: <autogenerated>:1 +0xa1 fp=0xc00035f3f8 sp=0xc00035f388 pc=0xa5ff31
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin.NextOrFailure(0xd6ab84, 0x3, 0xe8e0c0, 0xc00029b080, 0xe95f20, 0xc00003e060, 0xe9cc60, 0xc0003ba840, 0xc000315950, 0x0, ...)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/plugin/plugin.go:79 +0xe6 fp=0xc00035f520 sp=0xc00035f3f8 pc=0x7f4066
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/log.Logger.ServeDNS(0xe8e0c0, 0xc00029b080, 0xc0001e62c0, 0x1, 0x1, 0xda57f8, 0xe95f20, 0xc00003e060, 0xe9e880, 0xc000319680, ...)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/plugin/log/log.go:36 +0x39d fp=0xc00035f730 sp=0xc00035f520 pc=0xa4b1ed
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/log.(*Logger).ServeDNS(0xc0001dbe90, 0xe95f20, 0xc00003e060, 0xe9e880, 0xc000319680, 0xc000315950, 0xf0, 0x0, 0x1b)
Sep 30 14:51:22 vPF2 pfdns[9640]: <autogenerated>:1 +0xd6 fp=0xc00035f7e0 sp=0xc00035f730 pc=0xa4cd56
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin.NextOrFailure(0xd6ca0b, 0x6, 0xe8e080, 0xc0001dbe90, 0xe95f20, 0xc00003e060, 0xe9e880, 0xc000319680, 0xc000315950, 0x0, ...)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/plugin/plugin.go:79 +0xe6 fp=0xc00035f908 sp=0xc00035f7e0 pc=0x7f4066
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/errors.errorHandler.ServeDNS(0xe8e080, 0xc0001dbe90, 0xd6d0dd, 0x6, 0xc0001f2460, 0xe95f20, 0xc00003e060, 0xe9e880, 0xc000319680, 0xc000315950, ...)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/plugin/errors/errors.go:29 +0x170 fp=0xc00035fb00 sp=0xc00035f908 pc=0x9cad50
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/plugin/errors.(*errorHandler).ServeDNS(0xc0001dbec0, 0xe95f20, 0xc00003e060, 0xe9e880, 0xc000319680, 0xc000315950, 0x8, 0x20, 0xc0003ae6a0)
Sep 30 14:51:22 vPF2 pfdns[9640]: <autogenerated>:1 +0xd0 fp=0xc00035fba0 sp=0xc00035fb00 pc=0x9cc230
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/core/dnsserver.(*Server).ServeDNS(0xc000370cc0, 0xe95f20, 0xc00003e060, 0xe9e880, 0xc000319680, 0xc000315950)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/core/dnsserver/server.go:269 +0x366 fp=0xc00035fce8 sp=0xc00035fba0 pc=0x9830b6
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/inverse-inc/packetfence/go/coredns/core/dnsserver.(*Server).ServePacket.func1(0xe9e880, 0xc000319680, 0xc000315950)
Sep 30 14:51:22 vPF2 pfdns[9640]: /builds/inverse-inc/packetfence/go/coredns/core/dnsserver/server.go:111 +0x60 fp=0xc00035fd28 sp=0xc00035fce8 pc=0x984000
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0002b0b50, 0xe9e880, 0xc000319680, 0xc000315950)
Sep 30 14:51:22 vPF2 pfdns[9640]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:52 +0x44 fp=0xc00035fd50 sp=0xc00035fd28 pc=0x6f0624
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/miekg/dns.(*Server).serveDNS(0xc000322360, 0xc000319680)
Sep 30 14:51:22 vPF2 pfdns[9640]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:687 +0x292 fp=0xc00035fdd8 sp=0xc00035fd50 pc=0x6f3072
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/miekg/dns.(*Server).serve(0xc000322360, 0xc000319680)
Sep 30 14:51:22 vPF2 pfdns[9640]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:572 +0x2eb fp=0xc00035fea0 sp=0xc00035fdd8 pc=0x6f2c6b
Sep 30 14:51:22 vPF2 pfdns[9640]: github.com/miekg/dns.(*Server).worker(0xc000322360, 0xc000318a00)
Sep 30 14:51:22 vPF2 pfdns[9640]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:269 +0x200 fp=0xc00035ffd0 sp=0xc00035fea0 pc=0x6f0b90
Sep 30 14:51:22 vPF2 pfdns[9640]: runtime.goexit()
Sep 30 14:51:22 vPF2 pfdns[9640]: /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00035ffd8 sp=0xc00035ffd0 pc=0x460991
Sep 30 14:51:22 vPF2 pfdns[9640]: created by github.com/miekg/dns.(*Server).spawnWorker
Sep 30 14:51:22 vPF2 pfdns[9640]: /root/go/pkg/mod/github.com/miekg/dns@v1.1.3/server.go:284 +0x83
```

**Comment by julsemaan** [comment]
Happens here:
https://github.com/inverse-inc/packetfence/blob/v10.0.1/go/coredns/plugin/pfdns/pfconfig.go#L137

**Comment by julsemaan** [comment]
dupe of #5435, it was missing from maintenance/10.0
