### ISSUE TITLE
Firewall SSO is not working in 10.3

### ISSUE THREAD

**Issue by lyubomirtraykov** [inverse-inc/packetfence#6299]
**Describe the bug**
Firewall SSO is not working. I an getting errors in t pfsso.log.

`Apr 17 09:10:23 pf-01 pfsso[29819]: t=2021-04-17T09:10:23+0300 lvl=eror msg="Recovered panic: runtime error: invalid memory address or nil pointer dereference." pid=29819 request-uuid=989a9c94-9f43-11eb-9e04-005056aada8e`

**Comment by lyubomirtraykov** [comment]
Log in DEBUG:
```
Apr 19 11:51:37 pf-01 pfsso[29763]: t=2021-04-19T11:51:37+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=29763
Apr 19 11:51:37 pf-01 pfsso[29763]: t=2021-04-19T11:51:37+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=29763 PfconfigObject=keys|config::Firewall_SSO()
Apr 19 11:51:37 pf-01 pfsso[29763]: t=2021-04-19T11:51:37+0300 lvl=dbug msg="Adding object 10.10.10.1" pid=29763
Apr 19 11:51:37 pf-01 pfsso[29763]: t=2021-04-19T11:51:37+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=29763 PfconfigObject=hash_element|config::Firewall_SSO();10.10.10.1
Apr 19 11:51:37 pf-01 pfsso[29763]: t=2021-04-19T11:51:37+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=29763 PfconfigObject=hash_element|config::Firewall_SSO();10.10.10.1
Apr 19 11:51:37 pf-01 pfsso[29763]: t=2021-04-19T11:51:37+0300 lvl=dbug msg="Adding struct with address 0x1bb74b0 to the pool" pid=29763
Apr 19 11:51:37 pf-01 pfsso[29763]: t=2021-04-19T11:51:37+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=29763 PfconfigObject=element|interfaces::management_network(pf-01.local.traykovtrans.com)
Apr 19 11:53:24 pf-01 pfsso[29763]: t=2021-04-19T11:53:24+0300 lvl=dbug msg="Refreshing pfconfig pool" pid=29763 request-uuid=b37e3269-a0ec-11eb-ae93-005056aada8e
Apr 19 11:53:24 pf-01 pfsso[29763]: t=2021-04-19T11:53:24+0300 lvl=eror msg="Recovered panic: runtime error: invalid memory address or nil pointer dereference." pid=29763 request-uuid=b37e3269-a0ec-11eb-ae93-005056aada8e
Apr 19 11:53:24 pf-01 pfsso[29763]: t=2021-04-19T11:53:24+0300 lvl=dbug msg="Acquired lock for pfconfig pool" pid=29763 request-uuid=b37e3269-a0ec-11eb-ae93-005056aada8e
Apr 19 11:53:24 pf-01 pfsso[29763]: t=2021-04-19T11:53:24+0300 lvl=dbug msg="Refresh got lock ID" pid=29763 request-uuid=b37e3269-a0ec-11eb-ae93-005056aada8e LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
```

**Comment by julsemaan** [comment]
Can you provide the output of `journalctl -u packetfence-pfsso` while this is happening.

This will provide the full trace which is sent to STDOUT

Thanks

**Comment by lyubomirtraykov** [comment]
Journal:
```
Apr 19 14:42:59 pf-01.local.traykovtrans.com systemd[1]: Starting PacketFence PFSSO Service...
Apr 19 14:42:59 pf-01.local.traykovtrans.com /usr/local/pf/sbin/pfhttpd[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Adding struct with address 0x1bb7d28 to the pool" pid=29351
Apr 19 14:42:59 pf-01.local.traykovtrans.com /usr/local/pf/sbin/pfhttpd[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:
Apr 19 14:42:59 pf-01.local.traykovtrans.com /usr/local/pf/sbin/pfhttpd[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Adding struct with address 0x1bb7d28 to the pool" pid=29351
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfhttpd[29351]: Activating privacy features... done.
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfhttpd[29351]: Using configuration set log level: DEBUG
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfhttpd[29351]: Using configured statsd protocol: udp
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfhttpd[29351]: Using configured prefix: pfsso
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfhttpd[29351]: Couldn't initialize statsd client (write udp 127.0.0.1:41570->127.0.0.1:8125: write: connection refused)
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Adding object 10.10.10.1" pid=29351
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Adding struct with address 0x1bb74b0 to the pool" pid=29351
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:42:59+0300 lvl=dbug msg="Resource is not valid anymore. Was loaded at 0001-01-01 00:00:00 +0000 UTC" pid=
Apr 19 14:42:59 pf-01.local.traykovtrans.com systemd[1]: Started PacketFence PFSSO Service.
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfhttpd[29351]: Serving HTTP on port 8777
Apr 19 14:42:59 pf-01.local.traykovtrans.com pfhttpd[29351]: http://:8777 (only accessible on this machine)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:48+0300 lvl=dbug msg="Refreshing pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005056a
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:48+0300 lvl=eror msg="Recovered panic: runtime error: invalid memory address or nil pointer dereferenc
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: Recovered panic: runtime error: invalid memory address or nil pointer dereference.
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: goroutine 70 [running]:
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: runtime/debug.Stack(0x53, 0x0, 0x0)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: runtime/debug.PrintStack()
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /usr/local/go/src/runtime/debug/stack.go:16 +0x25
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/panichandler.outputPanic(0x130e600, 0xc00047f4d0, 0x102c6a0, 0x1b17620)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/panichandler/panichandler.go:37 +0x165
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/panichandler.Http(0x130e600, 0xc00047f4d0, 0x130b0c0, 0xc0005600e0)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/panichandler/panichandler.go:18 +0x6a
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: panic(0x102c6a0, 0x1b17620)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /usr/local/go/src/runtime/panic.go:969 +0x1b9
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/firewallsso.(*FirewallsContainer).All(0x0, 0x130e600, 0xc00047f710, 0xc00010d140)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/firewallsso/firewalls.go:29 +0x45
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/caddy/pfsso.PfssoHandler.handleUpdate(0x0, 0x0, 0x0, 0xc00010d140, 0x0, 0x130b0c0
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/caddy/pfsso/pfsso.go:167 +0x252
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/caddy/pfsso.PfssoHandler.ServeHTTP(0x12f7bc0, 0xc00007a840, 0xc0004eb2c0, 0xc0001
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/caddy/pfsso/pfsso.go:283 +0x145
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/caddy/pfconfig.PoolHandler.ServeHTTP(0x12f7d60, 0xc00007fc20, 0xc000041440, 0x1be
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/caddy/pfconfig/pool.go:82 +0x1d5
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/caddy/statsd.Statsd.ServeHTTP(0x12f7ce0, 0xc00007fc50, 0x130e580, 0xc0000ba010, 0
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/caddy/statsd/statsd.go:78 +0x16e
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:48+0300 lvl=dbug msg="Acquired lock for pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/caddy/logger.Logger.ServeHTTP(0x12f7da0, 0xc00007fc80, 0x130e600, 0xc0005254d0, 0
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/caddy/logger/logger.go:94 +0x182
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver.(*Server).serveHTTP(0xc00007a800, 0x130b0c0, 0xc
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver/server.go:457 +0x61c
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: github.com/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver.(*Server).ServeHTTP(0xc00007a800, 0x130b0c0, 0xc
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /builds/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver/server.go:391 +0x6d3
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: net/http.serverHandler.ServeHTTP(0xc000560000, 0x130b0c0, 0xc0005600e0, 0xc000326300)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /usr/local/go/src/net/http/server.go:2843 +0xa3
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: net/http.(*conn).serve(0xc0000c4280, 0x130e540, 0xc000440240)
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /usr/local/go/src/net/http/server.go:1925 +0x8ad
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: created by net/http.(*Server).Serve
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfhttpd[29351]: /usr/local/go/src/net/http/server.go:2969 +0x36c
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:48+0300 lvl=dbug msg="Refresh got lock ID" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005056aada8e
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:48+0300 lvl=dbug msg="Finished refresh of pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b23
Apr 19 14:44:48 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:48+0300 lvl=dbug msg="Refresh is releasing lock ID" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005
Apr 19 14:44:49 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:49+0300 lvl=dbug msg="Refreshing pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005056a
Apr 19 14:44:49 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:49+0300 lvl=dbug msg="Acquired lock for pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-
Apr 19 14:44:49 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:49+0300 lvl=dbug msg="Refresh got lock ID" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005056aada8e
Apr 19 14:44:49 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:49+0300 lvl=dbug msg="Finished refresh of pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b23
Apr 19 14:44:49 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:49+0300 lvl=dbug msg="Refresh is releasing lock ID" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005
Apr 19 14:44:50 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:50+0300 lvl=dbug msg="Refreshing pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005056a
Apr 19 14:44:50 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:50+0300 lvl=dbug msg="Acquired lock for pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-
Apr 19 14:44:50 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:50+0300 lvl=dbug msg="Refresh got lock ID" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005056aada8e
Apr 19 14:44:50 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:50+0300 lvl=dbug msg="Finished refresh of pfconfig pool" pid=29351 request-uuid=a5362f7f-a104-11eb-b23
Apr 19 14:44:50 pf-01.local.traykovtrans.com pfsso[29351]: t=2021-04-19T14:44:50+0300 lvl=dbug msg="Refresh is releasing lock ID" pid=29351 request-uuid=a5362f7f-a104-11eb-b239-005
```

**Comment by julsemaan** [comment]
Can you post `/usr/local/pf/conf/caddy-services/pfsso.conf`

**Comment by julsemaan** [comment]
The new pfsso binary will be ready in an hour or so via the maintenance branch
