### ISSUE TITLE
pfpki: get a cert using sscep enroll failed

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#6523]
**Describe the bug**
If I try to get a certificate using  `sscep enroll`, `pfpki` generates certificate but doesn't return it.

**To Reproduce**
1. `yum install packetfence-test --enablerepo=packetfence`
2. `cd /usr/local/pf/t/venom/; make install ; make dot1x_eap_tls_pfpki_no_teardown`

=> Your admin password should be "secret", it will replace RADIUS and HTTP certs.

2. Create a CSR to get a certificate using `sscep`:
```
# generate a key without passphrase
( _fd="client.key" ; _len="2048" ; \
openssl genrsa -out ${_fd} ${_len} )

# generate a CSR using private key
# use a challenge secret when defining CSR
# need to reply to some questions because we don't use a config file
( _fd="client.key" ; _fd_csr="client.csr" ; \
openssl req -out ${_fd_csr} -new -key ${_fd} )

# write ca.crt using InverseCA_user PKI profile with InverseCA CA
sscep getca -u http://172.17.17.12/scep/InverseCA_user -c ./ca.crt -i InverseCA  -v -d

# get certificate
# generate a client.crt but this one is generated based on informations in client.csr not based on user template
sscep enroll -c ./ca.crt  -k ./client.key -r ./client.csr -u http://172.17.17.12/scep/InverseCA_user -l ./client.crt -v -d -S sha1 -E aes
```

=> Certificate is generated by `pfpki` but [sscep output](https://gist.github.com/nqb/4a256f1f20ab7bc3d38e3dc32d36af5d) is weird and I didn't get a `client.crt `

**Expected behavior**
Certificate generated by `pfpki` and `client.crt`

**Additional context**
In logs:
```
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: level=info ts=2021-08-19T08:01:24.909920185Z caller=service_logging.go:22 component=scep_service method=GetCACaps err=null took=702ns
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: level=info ts=2021-08-19T08:01:24.909971745Z caller=endpoint.go:186 op=GetCACaps error=null took=52.977µs
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: level=info ts=2021-08-19T08:01:24.90999898Z caller=logutil.go:70 component=http method=GET status=200 proto=HTTP/1.1 host=127.0.0.1 user_agent= path="/api/v1/scep/Akamai_user?operation=GetCACaps"
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: level=info ts=2021-08-19T08:01:24.948522974Z caller=service_logging.go:47 component=scep_service method=PKIOperation err=null took=18.101756ms
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: level=info ts=2021-08-19T08:01:24.948554057Z caller=endpoint.go:186 op=PKIOperation error=null took=18.13425ms
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: level=info ts=2021-08-19T08:01:24.948569928Z caller=logutil.go:70 component=http method=POST status=200 proto=HTTP/1.1 host=127.0.0.1 user_agent= path="/api/v1/scep/Akamai_user?operation=PKIOperation"
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: Recovered panic: runtime error: invalid memory address or nil pointer dereference.
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: goroutine 214 [running]:
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: runtime/debug.Stack(0x53, 0x0, 0x0)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: runtime/debug.PrintStack()
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/panichandler.outputPanic(0x1320d20, 0xc000475110, 0x10336e0, 0x1995730)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/panichandler/panichandler.go:37 +0x165
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/panichandler.Http(0x1320d20, 0xc000475110, 0x131dc78, 0xc000504460)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/panichandler/panichandler.go:18 +0x6e
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: panic(0x10336e0, 0x1995730)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/caddy/pfpki/models.CA.SuccessNotify(...)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/caddy/pfpki/models/models.go:616
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/depot.(*Signer).SignCSR(0xc0003f8e10, 0xc0005421e0, 0x6, 0xc00056fdb8, 0x6)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/depot/signer.go:154 +0xb4e
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/server.ChallengeMiddleware.func1(0xc0005421e0, 0xb, 0x0, 0x0)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/server/csrsigner.go:42 +0x122
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/server.CSRSignerFunc.SignCSR(0xc00050a480, 0xc0005421e0, 0x1, 0x0, 0x0)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/server/csrsigner.go:24 +0x30
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/csrverifier.Middleware.func1(0xc0005421e0, 0xc00056fe60, 0xc000488b40, 0x11ec8c8)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/csrverifier/csrverifier.go:27 +0x8c
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/server.CSRSignerFunc.SignCSR(0xc00050a4b0, 0xc0005421e0, 0xc0000346c0, 0x0, 0x0)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/server/csrsigner.go:24 +0x30
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/server.(*service).PKIOperation(0xc0003f8e60, 0x1320d20, 0xc00050aae0, 0xc000220c00, 0xaae, 0xc00, 0x10, 0x10, 0xfdc9e0, 0x101, ...)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/server/service.go:84 +0x119
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/server.(*loggingService).PKIOperation(0xc00006d7c0, 0x1320d20, 0xc00050aae0, 0xc000220c00, 0xaae, 0xc00, 0x0, 0x0, 0x0, 0x0, ...)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/server/service_logging.go:53 +0x10e
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/server.MakeSCEPEndpoint.func1(0x1320d20, 0xc00050aae0, 0x10a3300, 0xc00050ab40, 0x2, 0xc00006dc20, 0x0, 0x2)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/server/endpoint.go:145 +0x3f5
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/scep/server.EndpointLoggingMiddleware.func1.1(0x1320d20, 0xc00050aae0, 0x10a3300, 0xc00050ab40, 0x0, 0x0, 0x0, 0x0)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/inverse-inc/scep@v0.0.0-20210513203155-0afeb79ee054/server/endpoint.go:188 +0x1ad
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/go-kit/kit/transport/http.Server.ServeHTTP(0xc00006d840, 0x11ec8f0, 0x11ec8f8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11ebda0, ...)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/go-kit/kit@v0.10.0/transport/http/server.go:121 +0x35a
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000488900, 0x131dc78, 0xc000504460, 0xc000491800)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xd3
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/caddy/pfpki/scep.ScepHandler(0xc00036e960, 0x131dc78, 0xc000504460, 0xc000491800)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/caddy/pfpki/scep/scep.go:98 +0xc8e
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/caddy/pfpki/handlers.ManageSCEP.func1(0x131dc78, 0xc000504460, 0xc000491800)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/caddy/pfpki/handlers/handlers.go:650 +0x187
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: net/http.HandlerFunc.ServeHTTP(0xc000433fa0, 0x131dc78, 0xc000504460, 0xc000491800)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/usr/local/go/src/net/http/server.go:2069 +0x44
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004880c0, 0x131dc78, 0xc000504460, 0xc000491600)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/root/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xd3
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/caddy/pfpki/types.Handler.ServeHTTP(0x130c300, 0xc00045f300, 0xc0004880c0, 0xc000187110, 0xc0002bfa60, 0x131dc78, 0xc000504460, 0xc000491500, 0x0, 0x0, ...)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/caddy/pfpki/types/types.go:95 +0x1ec
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/caddy/logger.Logger.ServeHTTP(0x130c460, 0xc000502360, 0x1320d20, 0xc00036e810, 0x0, 0x131dc78, 0xc000504460, 0xc000491400, 0xc0002aac00, 0x0, ...)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/caddy/logger/logger.go:94 +0x1a2
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver.(*Server).serveHTTP(0xc00045f2c0, 0x131dc78, 0xc000504460, 0xc000491300, 0xc000178088, 0xc000474f60, 0x1320d20)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver/server.go:457 +0x61c
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: github.com/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver.(*Server).ServeHTTP(0xc00045f2c0, 0x131dc78, 0xc000504460, 0xc000491300)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/builds/inverse-inc/packetfence/go/caddy/caddy/caddyhttp/httpserver/server.go:391 +0x6d3
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: net/http.serverHandler.ServeHTTP(0xc000504000, 0x131dc78, 0xc000504460, 0xc000491100)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/usr/local/go/src/net/http/server.go:2887 +0xa3
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: net/http.(*conn).serve(0xc00047f540, 0x1320d20, 0xc000150780)
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/usr/local/go/src/net/http/server.go:1952 +0x8cd
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: created by net/http.(*Server).Serve
Aug 19 08:01:24 pfdeb11dev pfhttpd[802]: 	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by julsemaan** [comment]
f081267 should address this issue

I found a case where if you don't have a CN in your CSR then the subject of the issued cert is empty but I'm not sure if that's an expected behavior where only the CN of the CSR is being used to issue the cert and it ignores the rest of the subject. That's minor though as it does work as expected AFAIK where the cert is issued by the right CA

**Comment by nqb** [comment]
I will test again.

**Comment by nqb** [comment]
It works as expected, after I pulled certificate, I'm able to use it for authentication and authorization.

I also noticed what you describe in your previous comment. I will open a dedicate issue for this one.
