### ISSUE TITLE
PFcron fails to start

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6891]
PF version:
````
[root@cluster1 pf]# rpm -qa packetfence
packetfence-11.2.0-20220211211137.470335896.0008.devel.el8.x86_64
````

logs:
````
Feb 15 09:34:28 cluster3.inverse.ca systemd[1]: Starting PacketFence pfcron Service...
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]: panic: interface conversion: interface {} is string, not float64
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]: goroutine 1 [running]:
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]: github.com/inverse-inc/packetfence/go/cron.NewBandwidthMaintenance(0x6c44a0)
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]:         /root/rpmbuild/centos-8/BUILD/packetfence-11.2.0/go/cron/bandwidth_maintenance.go:47 +0x5da
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]: github.com/inverse-inc/packetfence/go/cron.BuildJob({0xc00011a168, 0xc00010a5d0}, 0x70fbf3)
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]:         /root/rpmbuild/centos-8/BUILD/packetfence-11.2.0/go/cron/config.go:95 +0x55
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]: github.com/inverse-inc/packetfence/go/cron.GetConfiguredJobs(0x782370)
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]:         /root/rpmbuild/centos-8/BUILD/packetfence-11.2.0/go/cron/config.go:72 +0x17c
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]: main.main()
Feb 15 09:34:29 cluster3.inverse.ca pfcron[441913]:         /root/rpmbuild/centos-8/BUILD/packetfence-11.2.0/go/cmd/pfcron/main.go:167 +0x165
Feb 15 09:34:29 cluster3.inverse.ca systemd[1]: packetfence-pfcron.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by jrouzierinverse** [comment]
Can you try a config reload?

**Comment by lzammit** [comment]
You are correct that fixed it:
````
/usr/local/pf/bin/pfcmd fixpermissions
/usr/local/pf/bin/pfcmd pfconfig clear_backend
systemctl restart packetfence-config
/usr/local/pf/bin/pfcmd configreload hard
/usr/local/pf/bin/pfcmd service pf restart
````
