### ISSUE TITLE
v12(EL8): standalone upgrade is failing

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7185]
**Describe the bug**
If you upgrade an 11.2.0 setup to 12.0.0 (`devel`), package installation is failing.

**To Reproduce**
1. EL8 with 11.2 setup; post-configurator
2. Run an automated upgrade

**Additional context**
I have seen two different problems:

- `redis-cache` is started during upgrade process but it is not listening on 100.64.0.1. This is causing `pfperl-api` to stop:
```
Sep 07 14:27:12 nqb-11-2-el8 systemd[1]: packetfence-pfperl-api.service: start operation timed out. Terminating.
Sep 07 14:27:12 nqb-11-2-el8 systemd[1]: packetfence-pfperl-api.service: Supervising process 59988 which is not our child. We'll most likely not notice when it exits.
Sep 07 14:27:47 nqb-11-2-el8 pfperl-api-docker-wrapper[59988]: pfperl-api(8) ERROR: [mac:[undef]] error during cache set for namespace='configfiles', key='/usr/local/pf/conf/roles.conf', size=2446, expires='never', cache='Redis': Could >
Sep 07 14:27:47 nqb-11-2-el8 pfperl-api-docker-wrapper[59988]:  (CHI::Driver::_dispatch_error_msg)
```
- `api-frontend` and `httpd.admin_dispatcher` are failing to start at end of process:

```
Sep 07 14:28:56 nqb-11-2-el8 systemd[1]: Starting PacketFence API frontend Service...
Sep 07 14:28:57 nqb-11-2-el8 packetfence[91062]: -e(91062) WARN: Use of uninitialized value in concatenation (.) or string at /usr/local/pf/lib/pf/services/manager/roles/env_golang_service.pm line 41.
                                                  (pf::services::manager::roles::env_golang_service::__ANON__)
Sep 07 14:28:57 nqb-11-2-el8 perl[91062]: Use of uninitialized value in concatenation (.) or string at /usr/local/pf/lib/pf/services/manager/roles/env_golang_service.pm line 41.
Sep 07 14:28:57 nqb-11-2-el8 api-frontend-docker-wrapper[91257]: Running with args --sig-proxy=true --rm --name=api-frontend --add-host=containers-gateway.internal:host-gateway -h nqb-11-2-el8  -v /var/lib/mysql:/var/lib/mysql -v /usr/l>
Sep 07 14:28:57 nqb-11-2-el8 api-frontend-docker-wrapper[91269]: Error: No such container: api-frontend
Sep 07 14:28:57 nqb-11-2-el8 api-frontend-docker-wrapper[91269]: Error: No such container: 1
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: t=2022-09-07T14:28:58+0000 lvl=dbug msg="Memory configuration was never loaded. Considering config::FingerbankSettings() as invalid do the initial load." pid=7
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: panic: json: invalid number literal, trying to unmarshal "\"\"" into Number
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: goroutine 1 [running]:
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeJsonInterface({0x9a6726, 0x1a98a00}, {0xc00022e000, 0x21f, 0x240}, {0xf0d460, 0xc000072400})
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]:         /usr/local/pf/go/pfconfigdriver/fetch.go:223 +0x165
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: github.com/inverse-inc/packetfence/go/pfconfigdriver.decodeInterface({0x1272990, 0xc0000d2000}, {0x10dbdf1, 0xc00010b500}, {0xc00022e000, 0x17, 0x0}, {0xf0d460, 0xc0000724>
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]:         /usr/local/pf/go/pfconfigdriver/fetch.go:209 +0x65
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocket({0x1272990, 0xc0000d2000}, {0x1268a20, 0xc00010b500})
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]:         /usr/local/pf/go/pfconfigdriver/fetch.go:403 +0x6ec
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: github.com/inverse-inc/packetfence/go/pfconfigdriver.FetchDecodeSocketCache({0x1272990, 0xc0000d2000}, {0x1268a20, 0xc00010b500})
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]:         /usr/local/pf/go/pfconfigdriver/fetch.go:354 +0x1f1
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: github.com/inverse-inc/packetfence/go/fbcollectorclient.FromConfig({0x1272990, 0xc0000d2000})
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]:         /usr/local/pf/go/fbcollectorclient/client.go:151 +0x69
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]: github.com/inverse-inc/packetfence/go/fbcollectorclient.init()
Sep 07 14:28:58 nqb-11-2-el8 api-frontend-docker-wrapper[91277]:         /usr/local/pf/go/fbcollectorclient/client.go:147 +0x27
Sep 07 14:28:58 nqb-11-2-el8 systemd[1]: packetfence-api-frontend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 14:28:58 nqb-11-2-el8 systemd[1]: packetfence-api-frontend.service: Failed with result 'exit-code'.
Sep 07 14:28:58 nqb-11-2-el8 systemd[1]: Failed to start PacketFence API frontend Service.
```

I think this is related to the upgrade from 11.2 because I don't recall having such behavior when doing upgrades between 12.0 packages.

**Comment by julsemaan** [comment]
Was able to replicate and pushed a few fixes. I'm able to do the upgrade without these issues on EL8 now

**Comment by julsemaan** [comment]
@nqb, ready for you to retest and close

**Comment by nqb** [comment]
Tested and works as expected. Thanks!

I just noticed new messages in output of RPM installation (lines 138 to 142):

```
 134 FirewallD is not running
 135 Created symlink /etc/systemd/system/packetfence-base.target.wants/packetfence-redis-cache.service → /usr/lib/systemd/system/packetfence-redis-cache.service.
 136 Created symlink /etc/systemd/system/packetfence-base.target.wants/packetfence-config.service → /usr/lib/systemd/system/packetfence-config.service.
 137 Removed /etc/systemd/system/packetfence.target.wants/packetfence-iptables.service.
 138 Use of uninitialized value in string eq at /usr/local/pf/lib/pfconfig/util.pm line 98.             <<<<<
 139 Use of uninitialized value in string eq at /usr/local/pf/lib/pfconfig/util.pm line 98.
 140 Use of uninitialized value in string eq at /usr/local/pf/lib/pfconfig/util.pm line 98.
 141 Use of uninitialized value in string eq at /usr/local/pf/lib/pfconfig/util.pm line 98.
 142 Use of uninitialized value in string eq at /usr/local/pf/lib/pfconfig/util.pm line 98.
 143 Starting PacketFence Administration GUI...
```

**Comment by julsemaan** [comment]
Works fine now!
