### ISSUE TITLE
tests: get_id_of_radius_audit_log_entry is failing

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7776]
**Describe the problem**
```
            • get_id_of_radius_audit_log_entry FAILURE
    Testcase "get_id_of_radius_audit_log_entry", step #0: Assertion "result.statuscode ShouldEqual 200" failed. expected: 200  got: 404 (/usr/local/pf/t/venom/test_suites/wired_dot1x_eap_tls_scep/91_check_radius_audit_log.yml:89)
    Testcase "get_id_of_radius_audit_log_entry", step #0: Assertion "result.bodyjson.items.items0 ShouldContainKey id" failed. unable to cast <nil> of type <nil> to map[string]interface{} (/usr/local/pf/t/venom/test_suites/wired_dot1x_eap_tls_scep/91_check_radius_audit_log.yml:90)
```

**Mandatory informations**

 * Branch: Devel
 * Scenario: dot1x_eap_tls_deb11
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/4704653209
 
**Symptoms**
How the problem can be identified if it appears again ?

**Howto Fix**
Add retry and delay

**Comment by JeGoi** [comment]
Not sure how but:
```
Jul 24 14:40:40.048ESC[36m [INFO] [Check RADIUS audit log] [move_from_redis_to_db] [pfcron_command_line] ESC[0mStep #0 content is: "{\"script\":\" /usr/local/pf/sbin/pfcron flush_radius_audit_log\",\"typ
e\":\"exec\"}"
Jul 24 14:40:40.083ESC[37m [DEBU] [Check RADIUS audit log] [move_from_redis_to_db] [exec] ESC[0mresult of runTestStepExecutor: {Systemout: SystemoutJSON:<nil> Systemerr:panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/inverse-inc/packetfence/go/cron.(*FlushRadiusAuditLogJob).argsFromEntry(0xc0000fa500?, {0x0, 0x0, 0xc0000fa4b0?})
        /builds/inverse-inc/packetfence/go/cron/flush_radius_audit_log_job.go:167 +0x1058
github.com/inverse-inc/packetfence/go/cron.(*FlushRadiusAuditLogJob).buildQuery(0xc0000c9b38?, {0xc0000ac738, 0x1, 0xc0000a3da0?})
        /builds/inverse-inc/packetfence/go/cron/flush_radius_audit_log_job.go:158 +0x1e5
github.com/inverse-inc/packetfence/go/cron.(*FlushRadiusAuditLogJob).flushLogs(0xc00017b000?, {0xc0000ac738?, 0x1000?, 0x6feaa0?})
        /builds/inverse-inc/packetfence/go/cron/flush_radius_audit_log_job.go:75 +0x3f
github.com/inverse-inc/packetfence/go/cron.(*FlushRadiusAuditLogJob).Run(0xc0000eff10)
        /builds/inverse-inc/packetfence/go/cron/flush_radius_audit_log_job.go:63 +0x22f
main.runJobNow({0x7ffc14c80a6f, 0x16}, 0xf8aee56908?)
        /builds/inverse-inc/packetfence/go/cmd/pfcron/main.go:108 +0x304
main.main()
        /builds/inverse-inc/packetfence/go/cmd/pfcron/main.go:153 +0x1c5 SystemerrJSON:<nil> Err: Code:2 TimeSeconds:0.027987397}
````

**Comment by JeGoi** [comment]
@jrouzierinverse do you have an idea?

**Comment by JeGoi** [comment]
May be related to #7775 but not 100% sure.

**Comment by satkunas** [comment]
@JeGoi @abprasa validate on debian

**Comment by JeGoi** [comment]
@fdurand build (or explain how to) the deb.
thks

**Comment by JeGoi** [comment]
Looks fine since moved to 3.2.2 and increase buffer size (https://github.com/inverse-inc/freeradius-server/commit/7cbeb6b7f810ed233a2d4ffdc6cc19fdfd671cde)
