### ISSUE TITLE
tests: Waiting for domain to get an IP address...

### ISSUE THREAD

**Issue by JeGoi** [inverse-inc/packetfence#7984]
**Describe the problem**
```
==> pfel8dev: Waiting for domain to get an IP address...
/var/local/gitlab-runner/.vagrant.d/gems/3.1.4/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:9:in `block in wait_for': The specified wait_for timeout (2 seconds) was exceeded (Fog::Errors::TimeoutError)
	from /var/local/gitlab-runner/.vagrant.d/gems/3.1.4/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:6:in `loop'
	from /var/local/gitlab-runner/.vagrant.d/gems/3.1.4/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:6:in `wait_for'
	from /var/local/gitlab-runner/.vagrant.d/gems/3.1.4/gems/fog-core-2.3.0/lib/fog/core/model.rb:72:in `wait_for'
	from /var/local/gitlab-runner/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/driver.rb:303:in `get_ipaddress_from_domain'
	from /var/local/gitlab-runner/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/driver.rb:93:in `get_ipaddress'
	from /var/local/gitlab-runner/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/wait_till_up.rb:45:in `block (2 levels) in call'
```

No clue why, but it looks like the vagrant version is different between 11 (Vagrant 2.4.0) and 12+13 (Vagrant 2.3.7). 
I think it happens when we add issues with lab instancies BUT it should have been a fixed value.

**Mandatory informations**

 * Branch: DEVEL / 13.1
 * Scenario: ALL running under runner11
 * Pipelines URL:
   * https://gitlab.com/inverse-inc/packetfence/-/jobs/5951033416
 
**Symptoms**
How the problem can be identified if it appears again ?

**Comment by JeGoi** [comment]
Reinstall vagrant Vagrant 2.3.7 on runner-lab-cloud-11

**Comment by fdurand** [comment]
Closing after a review of the open issues: this tracked a CI failure tied to a specific runner, box or maintenance branch at the time, and it no longer applies to the current pipelines. If the same failure shows up again on a current branch, please open a new `tests:` issue with the fresh job link.
